# Generated by Django 3.1.12 on 2025-11-13 07:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('provider_id', models.CharField(max_length=24)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services_booking',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('provider_id', models.CharField(max_length=24)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'service_category',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category_name', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('original_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('experience_years', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(blank=True, default='Mon-Sat, 9AM-6PM', max_length=200)),
                ('service_area', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'service_provider',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id', unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Service Provider'), ('both', 'Both')], default='customer', max_length=20)),
                ('is_provider', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
